spring:
  application:
    name: eureka-server

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'